apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: examen-devops
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: change_me_root_password
  MYSQL_DATABASE: tienda_perritos
  MYSQL_USER: app_user
  MYSQL_PASSWORD: change_me_app_password
