apiVersion: apps/v1
kind: Deployment
metadata:
  name: despachos-api
  namespace: examen-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: despachos-api
  template:
    metadata:
      labels:
        app: despachos-api
    spec:
      containers:
        - name: despachos-api
          image: 409979112766.dkr.ecr.us-east-1.amazonaws.com/despacho-backend:eks-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DB_ENDPOINT
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 6
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 3
