apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: front-despacho-hpa
  namespace: examen-devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-despacho
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ventas-api-hpa
  namespace: examen-devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ventas-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: despachos-api-hpa
  namespace: examen-devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: despachos-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
